apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: web-app
spec:
  containers:
    - name: web-app
      image: kennychenfight/web-app
      ports:
        - containerPort: 8080